source "https://rubygems.org"

ruby "2.2.0"

gem "sinatra"
gem "sinatra-json"
gem "thin"
gem "rspec-sinatra"
gem "sass"
gem "public_suffix"
gem "net-ping"
gem "httparty"
gem "nokogiri"
gem "addressable"
gem "sinatra-flash"
gem "sanitize"
